name: gsm
channels:
  - conda-forge
  - defaults
dependencies:
  - notebook
  - huggingface_hub
  - datasets
  - coloredlogs
  - tqdm
  - pip
  - pip:
      - langchain-huggingface
      - langchain
      - ipywidgets
