name: gsm-cpu

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:

  # HuggingFace
  - transformers
  - datasets
  - accelerate

  # Core packages
  - numpy
  - pandas
  - tqdm
  - psutil

  # Jupyter
  - notebook
  - ipywidgets

  - pip
  - pip:
      - torch
      - openai
      - anthropic
      - google-genai
